name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies (backend)
        run: npm install
      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install
      - name: Lint backend
        run: npm run lint || true
      - name: Lint frontend
        run: |
          cd frontend
          npm run lint || true
      - name: Build frontend
        run: |
          cd frontend
          npm run build
